version: "3"
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mtc
    ports:
      - 443:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=mtc
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: